# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres:
    image: postgres:12.1
    ports:
      - 5432:5432
    volumes:
    -   ./data:/var/lib/postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 249281008