# Use postgres/example user/password credentials
version: '3.2'

services:

  postgres:
    image: postgres:12.1
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 249281008

volumes:
  data:
    driver: local